### ISSUE TITLE
Autodiff of solver clashes with Turing

### ISSUE THREAD

**Issue by jonasmac16** [SciML/DiffEqBayes.jl#124] opened 2020-01-22 17:27 UTC
Hi,

I raised that issue a while back on slack but never got around to raise it here. When you run the example from the documentation, it works fine with `Tsit5()` but using `Rodas5()` causes the following error 
```julia
Cannot determine ordering of Dual tags ForwardDiff.Tag{DiffEqDiffTools.UJacobianWrapper{LotkaVolterraTest1{var"#9#10",Nothing,Nothing,Nothing,Nothing,Nothing,Any,Any},Float64,Array{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#31"{Turing.Core.RandomVariables.VarInfo{NamedTuple{(:theta1, :σ1),Tuple{Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:theta1},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{Turing.Core.RandomVariables.VarName{:theta1},1},Array{Float64,1},Array{Set{Turing.Selector},1}},Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:σ1},Int64},Array{InverseGamma{Float64},1},Array{Turing.Core.RandomVariables.VarName{:σ1},1},Array{Float64,1},Array{Set{Turing.Selector},1}}}},Float64},Turing.Model{Tuple{:theta1,:σ1},Tuple{:x},DiffEqBayes.var"#mf#10"{Array{InverseGamma{Float64},1},DiffEqBayes.var"#8#17",Array{Symbol,1},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},LotkaVolterraTest1{var"#9#10",Nothing,Nothing,Nothing,Nothing,Nothing,Any,Any},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},Rodas5{0,true,DefaultLinSolve,DataType},Array{Float64,1},Array{Truncated{Normal{Float64},Continuous,Float64},1}},Array{Float64,2},NamedTuple{(:x,),Tuple{Array{Float64,2}}}},Turing.Sampler{Turing.Inference.NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.Adaptation.DiagEuclideanMetric},Turing.Inference.SamplerState{Turing.Core.RandomVariables.VarInfo{NamedTuple{(:theta1, :σ1),Tuple{Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:theta1},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{Turing.Core.RandomVariables.VarName{:theta1},1},Array{Float64,1},Array{Set{Turing.Selector},1}},Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:σ1},Int64},Array{InverseGamma{Float64},1},Array{Turing.Core.RandomVariables.VarName{:σ1},1},Array{Float64,1},Array{Set{Turing.Selector},1}}}},Float64}}}},Float64},Float64,2},1}},ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#31"{Turing.Core.RandomVariables.VarInfo{NamedTuple{(:theta1, :σ1),Tuple{Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:theta1},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{Turing.Core.RandomVariables.VarName{:theta1},1},Array{Float64,1},Array{Set{Turing.Selector},1}},Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:σ1},Int64},Array{InverseGamma{Float64},1},Array{Turing.Core.RandomVariables.VarName{:σ1},1},Array{Float64,1},Array{Set{Turing.Selector},1}}}},Float64},Turing.Model{Tuple{:theta1,:σ1},Tuple{:x},DiffEqBayes.var"#mf#10"{Array{InverseGamma{Float64},1},DiffEqBayes.var"#8#17",Array{Symbol,1},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},LotkaVolterraTest1{var"#9#10",Nothing,Nothing,Nothing,Nothing,Nothing,Any,Any},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem},Rodas5{0,true,DefaultLinSolve,DataType},Array{Float64,1},Array{Truncated{Normal{Float64},Continuous,Float64},1}},Array{Float64,2},NamedTuple{(:x,),Tuple{Array{Float64,2}}}},Turing.Sampler{Turing.Inference.NUTS{Turing.Core.ForwardDiffAD{40},(),AdvancedHMC.Adaptation.DiagEuclideanMetric},Turing.Inference.SamplerState{Turing.Core.RandomVariables.VarInfo{NamedTuple{(:theta1, :σ1),Tuple{Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:theta1},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{Turing.Core.RandomVariables.VarName{:theta1},1},Array{Float64,1},Array{Set{Turing.Selector},1}},Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:σ1},Int64},Array{InverseGamma{Float64},1},Array{Turing.Core.RandomVariables.VarName{:σ1},1},Array{Float64,1},Array{Set{Turing.Selector},1}}}},Float64}}}},Float64},Float64,2}}() and ForwardDiff.Tag{Turing.Core.var"#f#31"{Turing.Core.RandomVariables.VarInfo{NamedTuple{(:theta1, :σ1),Tuple{Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:theta1},Int64},Array{Truncated{Normal{Float64},Continuous,Float64},1},Array{Turing.Core.RandomVariables.VarName{:theta1},1},Array{Float64,1},Array{Set{Turing.Selector},1}},Turing.Core.RandomVariables.Metadata{Dict{Turing.Core.RandomVariables.VarName{:σ1},Int64},Array{InverseGamma{Float64},1},Array{Turing.Core.RandomVariables.VarName{:σ1},1},Array{Float64,1},Array{Set{Turing.Selector},1}}}},Float64},Turing.Model{Tuple{:theta1,:σ1},Tuple{:x},DiffEqBayes.var"#mf#10"{Array{InverseGamma{Float64},1},DiffEqBayes.var"#8#17",Array{Symbol,1},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,Array{Float64,1},LotkaVolterraTest1{va...
```
, which goes away if you switch off autodiff of the solver via `Rodas5(autodiff=false)`. It looks like that the `AD` of `Turing` and `DifferentialEquations` are clashing with one another. 

A MWE which showes the issue:

```julia
using DiffEqBayes
using DifferentialEquations
using ParameterizedFunctions
using Distributions

f1 = @ode_def_bare LotkaVolterraTest1 begin
 dx = a*x - x*y
 dy = -3*y + x*y
end a

p = [1.5]
u0 = [1.0,1.0]
tspan = (0.0,10.0)
prob1 = ODEProblem(f1,u0,tspan,p)

σ = 0.01                         # noise, fixed for now
t = collect(range(1,stop=10,length=10))   # observation times
sol = solve(prob1,Tsit5())

randomized = VectorOfArray([(sol(t[i]) + σ * randn(2)) for i in 1:length(t)])
data = convert(Array,randomized)

priors = [Truncated(Normal(1.5,0.1),0,2)]

# works
bayesian_result_turing_tsit5 = turing_inference(prob1,Tsit5(),t,data,priors;num_samples=500) 
# works
bayesian_result_turing_rodas5_noautodiff = turing_inference(prob1,Rodas5(autodiff=false),t,data,priors;num_samples=500)
#doesn't work
bayesian_result_turing_rodas5 = turing_inference(prob1,Rodas5(),t,data,priors;num_samples=500) ```

**Comment by mohamed82008** [comment] 2020-01-25 01:39
This is working for me on #127.

**Comment by mohamed82008** [comment] 2020-01-25 01:40
Actually it's not, sorry I confused this issue with another.

**Comment by jonasmac16** [comment] 2020-01-27 10:43
Do you know where exactly the issue lies causing this error?

**Comment by mohamed82008** [comment] 2020-01-27 23:19
It seems like a ForwardDiff bug. I would find the exact function call that errors and exact numbers then open an issue there.

**Comment by ChrisRackauckas** [comment] 2020-01-28 14:29
Probably need to awaken the great @jrevels . The issue likely comes from the fact that in SparseDiffTools we have to define our own Dual tags since we need to build the color vectors.

https://github.com/JuliaDiff/SparseDiffTools.jl/blob/master/src/differentiation/compute_jacobian_ad.jl#L46

**Comment by jonasmac16** [comment] 2020-02-04 14:51
As suggested, I have opened an issue at ForwardDiff ( https://github.com/JuliaDiff/ForwardDiff.jl/issues/446#issue-557453456 ). Is there anything I can do to help to resolve this?

**Comment by ChrisRackauckas** [comment] 2020-02-04 15:53
@jrevels James is in town tomorrow: you want to join our dinner at Pepper Sky and discuss this a bit?

**Comment by jonasmac16** [comment] 2020-03-13 10:14
Hi, has there been any progress on this? Can I help somehow?

**Comment by ChrisRackauckas** [comment] 2020-05-01 13:35
Fixed by https://github.com/JuliaDiff/SparseDiffTools.jl/pull/105 and https://github.com/SciML/DiffEqBayes.jl/pull/157 will be a regression test for this.

**Closed** 2020-05-01 17:54 UTC
